Adding files to trigger modal as designed
DrDroidLab/PlayBooks pull request #459
Opened 2024-08-14 07:49 UTC by rishsanyal

There's a small issue for first-time users where every page will show the Product Update Modal to the customer.

Playbooks currently depends on setting the last-login time cookie to know if this modal should be displayed or not. There's 2 issues with this:

New customers from the same browser won't get the chance to sign up for product updates
A first time customer will just face annoyances for the first time they interact with Playbooks' platform.
This PR fixes that by ensuring that on registering we focus on the new customer through setting the option in the redux store and clearing the last-login time cookie on re-registering

I've added 2 videos below. The first one shows the issue and the second validates the fix.

Issue:
https://github.com/user-attachments/assets/2f6c0db1-cc50-4bad-8b9c-fd38516a8887

Validated Fix:

https://github.com/user-attachments/assets/7abf09e4-aaa2-4036-aa77-f4ea7a6cbe93

2024-08-14 07:51 UTC, rishsanyal commented
@droid-mohit @jayeshsadhwani99 Thank you for your patience and help. Created the new PR here.

 Apologies for the confusion with the previous PR once again.

2024-08-19 15:13 UTC, sidPhoenix17 commented
@jayeshsadhwani99 can you please review this PR?

2024-08-20 05:52 UTC, dimittal commented
@rishsanyal Please update your branch from `main` branch. This was commented a while ago.
Also, please edit the PR to be raised against `integration` branch. That is where all changes go before it is merged into main.

2024-08-21 16:26 UTC, jayeshsadhwani99 commented on helm/charts/web/templates/web-ingress.yaml
why is this changed

2024-08-21 16:26 UTC, jayeshsadhwani99 commented on helm/charts/web/templates/service.yaml
and this file too

2024-08-21 16:51 UTC, rishsanyal commented on helm/charts/web/templates/web-ingress.yaml
My understanding is that when I moved that target branch from `main` to `integration` these changes came with it since they exist in main but not in integration. 

I wanted to ask you, should they be integrated in main as well? I tried removing them from the PR but that let to more merge conflicts and I wasn't sure if we want that.

2024-08-21 16:51 UTC, rishsanyal commented on helm/charts/web/templates/service.yaml
Same as above

2024-08-22 07:47 UTC, jayeshsadhwani99 commented on helm/charts/web/templates/web-ingress.yaml
sure

2024-08-22 08:05 UTC, jayeshsadhwani99 requested changes
The expected behaviour is:
1. We click on Yes, the yes handler, or in your case the single handler works
2. We click on No, similar behaviour
3. When we click outside or click on the close button on the top right, It has the same behaviour as no.

In your case, yes and no work fine but when clicked outside the modal or clicked on cross, the same bug still arises. 

There are 2 solutions I see:
1. You can add the same event as in no and do it that way (simpler in this case)
2. You can refresh the page whenever there is an event on this modal. Since everything is stored in localstorage should work without any problems since the state will be refreshed

You can do any of the above or if you have a better solution you can also do that

2024-08-23 17:28 UTC, rishsanyal commented
@jayeshsadhwani99 : Thank you for catching that. I've updated the code to register the event as the user not signing up for updates now.

2024-08-27 09:18 UTC, jayeshsadhwani99 requested changes
The same issue occurs when the user clicks on the close icon, please change line 35 too

2024-09-05 06:30 UTC, merged